@host=http://localhost:5118

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Ayoub",
    "lastName": "chaib",
    "email": "ayoub.chaib.dev@gmail.com",
    "password": "Ayoub123"
}